
export const SYNTH_UI_SELECT_KNOB = "SYNTH_UI_SELECT_KNOB"
export const SYNTH_UI_DESELECT_KNOB = "SYNTH_UI_DESELECT_KNOB";

export const SYNTH_SET_FLAG = "SYNTH_SET_FLAG";
export const SYNTH_SET_LEVEL = "SYNTH_SET_LEVEL";
export const SYNTH_SET_CHOICE = "SYNTH_SET_CHOICE";
export const SYNTH_SET_DATA = "SYNTH_SET_DATA";

export const SYNTH_TOGGLE_FLAG = "SYNTH_TOGGLE_FLAG";
export const SYNTH_CHANGE_LEVEL = "SYNTH_CHANGE_LEVEL";
export const SYNTH_CHANGE_CHOICE = "SYNTH_CHANGE_CHOICE";
export const SYNTH_INCR_LEVEL = "SYNTH_INCR_LEVEL";
export const SYNTH_DECR_LEVEL = "SYNTH_DECR_LEVEL";
export const SYNTH_NEXT_CHOICE = "SYNTH_NEXT_CHOICE";
export const SYNTH_PREV_CHOICE = "SYNTH_PREV_CHOICE";

export const MIDI_CONTROLLER_DISABLE = "MIDI_CONTROLLER_DISABLE";
export const MIDI_CONTROLLER_ENABLE = "MIDI_CONTROLLER_ENABLE";

export const PATCH_SELECTION = "PATCH_SELECTION_"
export const PATCH_SELECTION_SET = PATCH_SELECTION + "SET";
export const PATCH_SELECTION_INCR = PATCH_SELECTION + "INCR";
export const PATCH_SELECTION_DECR = PATCH_SELECTION + "DECR";
export const PATCH_SET_NAME = "PATCH_SET_NAME";
export const PATCH_SAVE_SYNTH = "PATCH_SAVE_SYNTH";
export const PATCH_STORE_DATA = "PATCH_STORE_DATA";

