
export const SYNTH_UI_SELECT_KNOB = "SYNTH_UI_SELECT_KNOB"
export const SYNTH_UI_DESELECT_KNOB = "SYNTH_UI_DESELECT_KNOB";

export const SYNTH_TOGGLE_FLAG = "SYNTH_TOGGLE_FLAG";
export const SYNTH_SET_LEVEL = "SYNTH_SET_LEVEL";
export const SYNTH_INCR_LEVEL = "SYNTH_INCR_LEVEL";
export const SYNTH_DECR_LEVEL = "SYNTH_DECR_LEVEL";
export const SYNTH_SET_CHOICE = "SYNTH_SET_CHOICE";
export const SYNTH_NEXT_CHOICE = "SYNTH_NEXT_CHOICE";
export const SYNTH_PREV_CHOICE = "SYNTH_PREV_CHOICE";
