

export const POLYMOD_SOURCE_FILTER_ENV = "POLYMOD_SOURCE_FILTER_ENV";
export const POLYMOD_SOURCE_OSCILLATOR_B = "POLYMOD_SOURCE_OSCILLATOR_B";
export const POLYMOD_DEST_FREQUENCY_A = "POLYMOD_DEST_FREQUENCY_A";
export const POLYMOD_DEST_FILTER = "POLYMOD_DEST_FILTER";

export const LFO_FREQUENCY = "LFO_FREQUENCY";
export const LFO_RANGE = "LFO_RANGE";
export const LFO_SHAPE = "LFO_SHAPE";
export const LFO_DEPTH = "LFO_DEPTH";
export const LFO_DELAY = "LFO_DELAY";
export const LFO_DEST_TARGET = "LFO_DEST_TARGET";
export const LFO_DEST_FREQUENCY = "LFO_DEST_FREQUENCY";
export const LFO_DEST_PULSE_WIDTH = "LFO_DEST_PULSE_WIDTH";
export const LFO_DEST_FILTER = "LFO_DEST_FILTER";
export const LFO_DEST_AMPLIFIER = "LFO_DEST_AMPLIFIER";

export const VIBRATO_FREQUENCY = "VIBRATO_FREQUENCY";
export const VIBRATO_DEPTH = "VIBRATO_DEPTH";

export const UNISON_TRACK = "UNISON_TRACK";
export const UNISON_DETUNE = "UNISON_DETUNE";
export const UNISON_TRACK_PATTERN = "UNISON_TRACK_PATTERN";

export const OSCILLATOR_A_FREQUENCY = "OSCILLATOR_A_FREQUENCY";
export const OSCILLATOR_A_SYNC = "OSCILLATOR_A_SYNC";
export const OSCILLATOR_A_SHAPE_SAWTOOTH = "OSCILLATOR_A_SHAPE_SAWTOOTH";
export const OSCILLATOR_A_SHAPE_TRIANGLE = "OSCILLATOR_A_SHAPE_TRIANGLE";
export const OSCILLATOR_A_SHAPE_PULSE = "OSCILLATOR_A_SHAPE_PULSE";
export const OSCILLATOR_A_PULSE_WIDTH = "OSCILLATOR_A_PULSE_WIDTH";

export const OSCILLATOR_B_FREQUENCY = "OSCILLATOR_B_FREQUENCY";
export const OSCILLATOR_B_FINE = "OSCILLATOR_B_FINE";
export const OSCILLATOR_B_SHAPE_SAWTOOTH = "OSCILLATOR_B_SHAPE_SAWTOOTH";
export const OSCILLATOR_B_SHAPE_TRIANGLE = "OSCILLATOR_B_SHAPE_TRIANGLE";
export const OSCILLATOR_B_SHAPE_PULSE = "OSCILLATOR_B_SHAPE_PULSE";
export const OSCILLATOR_B_PULSE_WIDTH = "OSCILLATOR_B_PULSE_WIDTH";

export const MIXER_OSCILLATOR_A_LEVEL = "MIXER_OSCILLATOR_A_LEVEL";
export const MIXER_OSCILLATOR_B_LEVEL = "MIXER_OSCILLATOR_B_LEVEL";

export const FILTER_CUTOFF = "FILTER_CUTOFF";
export const FILTER_RESONANCE = "FILTER_RESONANCE";
export const FILTER_ENVELOPE_AMOUNT = "FILTER_ENVELOPE_AMOUNT";
export const FILTER_KEYBOARD_TRACK = "FILTER_KEYBOARD_TRACK";
export const FILTER_ENVELOPE_CURVE = "FILTER_ENVELOPE_CURVE";
export const FILTER_ENVELOPE_RATE = "FILTER_ENVELOPE_RATE";
export const FILTER_ENVELOPE_ATTACK = "FILTER_ENVELOPE_ATTACK";
export const FILTER_ENVELOPE_DECAY = "FILTER_ENVELOPE_DECAY";
export const FILTER_ENVELOPE_SUSTAIN = "FILTER_ENVELOPE_SUSTAIN";
export const FILTER_ENVELOPE_RELEASE = "FILTER_ENVELOPE_RELEASE";
export const FILTER_ENVELOPE_VELOCITY = "FILTER_ENVELOPE_VELOCITY";

export const AMPLIFIER_ENVELOPE_CURVE = "AMPLIFIER_ENVELOPE_CURVE";
export const AMPLIFIER_ENVELOPE_RATE = "AMPLIFIER_ENVELOPE_RATE";
export const AMPLIFIER_ENVELOPE_ATTACK = "AMPLIFIER_ENVELOPE_ATTACK";
export const AMPLIFIER_ENVELOPE_DECAY = "AMPLIFIER_ENVELOPE_DECAY";
export const AMPLIFIER_ENVELOPE_SUSTAIN = "AMPLIFIER_ENVELOPE_SUSTAIN";
export const AMPLIFIER_ENVELOPE_RELEASE = "AMPLIFIER_ENVELOPE_RELEASE";
export const AMPLIFIER_ENVELOPE_VELOCITY = "AMPLIFIER_ENVELOPE_VELOCITY";

export const PERFORMANCE_BEND_WHEEL_TARGET = "PERFORMANCE_BEND_WHEEL_TARGET";
export const PERFORMANCE_BEND_WHEEL_RANGE = "PERFORMANCE_BEND_WHEEL_RANGE";
export const PERFORMANCE_MOD_WHEEL_TARGET = "PERFORMANCE_MOD_WHEEL_TARGET";
export const PERFORMANCE_MOD_WHEEL_RANGE = "PERFORMANCE_MOD_WHEEL_RANGE";
export const PERFORMANCE_KEYBOARD_KEY_ASSIGN = "PERFORMANCE_KEYBOARD_KEY_ASSIGN";
export const PERFORMANCE_KEYBOARD_GLIDE = "PERFORMANCE_KEYBOARD_GLIDE";

export const GLOBAL_FREQUENCY_STEP = "GLOBAL_FREQUENCY_STEP";
export const GLOBAL_ARPEGGIATOR_CLOCK = "GLOBAL_ARPEGGIATOR_CLOCK";
